server:
  port: 8085

spring:
  application:
    name: btbs-workflow-service
  datasource:
    url: jdbc:mysql://47.96.89.84:3306/btbs_workflow?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
    username: root
    password: MiZhi001
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:   #下面为连接池的补充设置，应用到上面数据源中
      initialSize: 4 #初始化大小
      minIdle: 4 #最小
      maxActive: 32 #最大
      maxWait: 1000  #获取连接等待超时的时间
      timeBetweenEvictionRunsMillis: 30000 #间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 5000 #一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20

security:
  basic:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/ #如果是集群，配置成多个服务器，以","分割
  #      defaultZone: http://47.96.89.84:8001/eureka/
  #      defaultZone: http://192.168.18.133:8001/eureka/
  instance:
    prefer-ip-address: true
#    ip-address: 192.168.18.52